# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev", "prod" ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  AWS_ECR: ${{ secret.AWS_ECR }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          # Aquí tus tests bajan el modelo y los datos de S3 y prueban
          pytest tests/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR (O DockerHub)
        # Usar action oficial de AWS para login
        
      - name: Build Docker Image
        run: |
          docker build -t mi-app:${{ github.sha }} .
      
      - name: Push Docker Image
        run: |
          # Push a tu registro
      
      - name: Deploy to Cloud
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "Desplegando a PROD..."
            # Aquí va el script para actualizar tu servicio PROD
            # Ejemplo: SSH a tu EC2 y reiniciar el contenedor de prod con la nueva imagen
          else
            echo "Desplegando a DEV..."
            # Script para actualizar servicio DEV
          fi
